extends: 
  - eslint:recommended
  - plugin:react/recommended
  - plugin:prettier/recommended
  - prettier
parser: babel-eslint
parserOptions:
  ecmaVersion: 2018
settings: 
  react:
    version: detect
plugins: 
  - prettier
  - react
env:
  browser: true
  node: true
rules:
  no-console: off
  'prettier/prettier': error
